CREATE OR REPLACE PACKAGE PK_PAQUETERAFASE AS

	FUNCTION FU_TOTALPRODUCTOS(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

	FUNCTION FU_IVATOTAL(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

	FUNCTION FU_TOTALSINIVA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

	FUNCTION FU_CREARFACTURA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN VARCHAR2;

	FUNCTION FU_COMPROBARPAGO(NUMERO_TARJETA_INGRESADA IN BANCO.NUMERO_TARJETA%TYPE, CODIGOVV IN BANCO.CVV%TYPE, FECHA_VEN IN BANCO.FECHA_EXP%TYPE)
	RETURN VARCHAR2;

	PROCEDURE PR_ACTUALIZARSTOCK(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE);

END PK_PAQUETERAFASE;