CREATE OR REPLACE PACKAGE BODY PK_PAQUETERAFASE AS

	FUNCTION FU_TOTALPRODUCTOS(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;
		IVA NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.CANTIDAD * VALORES.PRECIO;
			IVA := VALORPRODUCTO * VALORES.IVA;
			TOTAL := TOTAL + VALORPRODUCTO + IVA;
		END LOOP;

		RETURN TOTAL;
	END;

	FUNCTION FU_IVATOTAL(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;
		IVA NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.PRECIO;
			IVA := VALORPRODUCTO * VALORES.IVA;
			TOTAL := TOTAL + IVA;
		END LOOP;

		RETURN TOTAL;
	END;

	FUNCTION FU_TOTALSINIVA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.CANTIDAD * VALORES.PRECIO;
			TOTAL := TOTAL + VALORPRODUCTO;
		END LOOP;

		RETURN TOTAL;
	END;


END PK_PAQUETERAFASE;