CREATE OR REPLACE PACKAGE PK_PAQUETERAFASE AS

	FUNCTION FU_TOTALPRODUCTOS(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

	FUNCTION FU_IVATOTAL(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

	FUNCTION FU_TOTALSINIVA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	RETURN NUMBER;

END PK_PAQUETERAFASE;