CREATE OR REPLACE PACKAGE BODY PK_PAQUETERAFASE AS

	FUNCTION FU_TOTALPRODUCTOS(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;
		IVA NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO AND PK_PEDIDO = 22;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.CANTIDAD * VALORES.PRECIO;
			IVA := VALORPRODUCTO * VALORES.IVA;
			TOTAL := TOTAL + VALORPRODUCTO + IVA;
		END LOOP;

		RETURN TOTAL;
	END FU_TOTALPRODUCTOS;

	FUNCTION FU_IVATOTAL(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;
		IVA NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO AND PK_PEDIDO = 22;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.PRECIO;
			IVA := VALORPRODUCTO * VALORES.IVA;
			TOTAL := TOTAL + IVA;
		END LOOP;

		RETURN TOTAL;
	END FU_IVATOTAL;

	FUNCTION FU_TOTALSINIVA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE) RETURN NUMBER
	IS

		TOTAL NUMBER;
		VALORPRODUCTO NUMBER;

		CURSOR C_TOTALPROD IS
		SELECT DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA FROM PED, DEPE, INV, PROD WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND  INV.ID_PRODUCTO = PROD.ID_PRODUCTO AND PK_PEDIDO = 22;
		
	BEGIN
	TOTAL := 0;
		FOR VALORES IN C_TOTALPROD LOOP
			VALORPRODUCTO := VALORES.CANTIDAD * VALORES.PRECIO;
			TOTAL := TOTAL + VALORPRODUCTO;
		END LOOP;

		RETURN TOTAL;
	END FU_TOTALSINIVA;

	PROCEDURE PR_CREARFACTURA(PK_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE)
	IS

		SENTENCIA VARCHAR2(2000);

	BEGIN
		SENTENCIA := 'CREATE OR REPLACE VIEW FACTURA' || PK_PEDIDO || ' AS SELECT PED.ID_PEDIDO, DEPE.CANTIDAD AS CANTIDAD, INV.PRECIO_BASE AS PRECIO, PROD.IVA AS IVA, (SELECT PK_PAQUETERAFASE.FU_TOTALPRODUCTOS(' || PK_PEDIDO || ') FROM DUAL) AS PRECIOCOMPLETO, (SELECT PK_PAQUETERAFASE.FU_IVATOTAL(' || PK_PEDIDO || ') FROM DUAL) AS IVACOMPLETO, (SELECT PK_PAQUETERAFASE.FU_TOTALSINIVA(' || PK_PEDIDO || ') FROM DUAL) AS PRECIOSINIVA, ENV.METODO_PAGO FROM PED, DEPE, INV, PROD, ENV WHERE PED.ID_PEDIDO = DEPE.ID_PEDIDO AND DEPE.ID_PRODUCTO = PROD.ID_PRODUCTO AND INV.ID_PRODUCTO = PROD.ID_PRODUCTO AND PED.ID_PEDIDO = ENV.ID_PEDIDO AND PED.ID_PEDIDO = ' || PK_PEDIDO;
		EXECUTE IMMEDIATE SENTENCIA;


	END PR_CREARFACTURA;

END PK_PAQUETERAFASE;

