SELECT ID_PRODUCTO,NOMBRE_PRODUCTO,MARCA_PRODUCTO,REFERENCIA_PRODUCTO,
	CARACTERISTICAS_PRODUCTO,FOTO,ID_SUBCATEGORIA,IVA,UNIDAD_MEDIDA
	FROM prod,inv,ciu,prove WHERE prod.ID_PRODUCTO = inv.ID_PRODUCTO
	AND ciu.ID_CIUDAD = inv.ID_CIUDAD AND prove.ID_PROVEEDOR = inv.ID_PROVEEDOR
	AND ciu.ID_CIUDAD = ciudad
	AND NOMBRE_PRODUCTO LIKE UPPER('%producto_buscado%') ORDER BY NOMBRE_PRODUCTO ASC;


CREATE VIEW INVENTARIO_RAFASE AS
(SELECT ciu.ID_CIUDAD,prove.ID_PROVEEDOR,categ.ID_CATEGORIA,categ.NOMBRE_CATEGORIA,categ.DESCRIPCION_CATEGORIA,
	subcat.ID_SUBCATEGORIA,subcat.NOMBRE_SUBCATEGORIA,prod.ID_PRODUCTO,prod.NOMBRE_PRODUCTO,
	prod.MARCA_PRODUCTO,prod.REFERENCIA_PRODUCTO,prod.CARACTERISTICAS_PRODUCTO,prod.FOTO,
	prod.ID_SUBCATEGORIA,prod.IVA,prod.UNIDAD_MEDIDA,inv.EXISTENCIAS,inv.PRECIO_BASE
	FROM prod,inv,ciu,prove,subcat,categ
	WHERE prod.ID_PRODUCTO = inv.ID_PRODUCTO
	AND ciu.ID_CIUDAD = inv.ID_CIUDAD AND prove.ID_PROVEEDOR = inv.ID_PROVEEDOR
	AND prod.ID_SUBCATEGORIA = subcat.ID_SUBCATEGORIA AND subcat.ID_CATEGORIA = categ.ID_CATEGORIA);

SELECT * FROM INVENTARIO_RAFASE WHERE ID_CIUDAD = ciudad
	AND NOMBRE_PRODUCTO LIKE UPPER('%producto_buscado%') ORDER BY NOMBRE_PRODUCTO ASC;