/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-Aug-2020 8:39:22 PM 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Administrador  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Categoria  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Ciudad  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Detalle_Pedido  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Direccion  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Envio  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Inventario  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Pedido  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Producto  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Proveedor  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Subcategoria  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     TarjetaCredito  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Telefono  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Tienda  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE     Usuario  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE    Administrador 
(
	  ID_ADMINISTRADOR  NUMBER(38) NOT NULL,    -- N. de identificacion del administrador
	  NOMBRE_ADMINISTRADOR  VARCHAR2(50) NOT NULL,    -- Nombre del administrador
	  EMAIL  VARCHAR2(50) NOT NULL,    -- Correo electrónico del administrador
	  CONTRASENA  VARCHAR2(50) NOT NULL    -- Contraseña del administrador
)
;

CREATE TABLE    Categoria 
(
	  ID_CATEGORIA  NUMBER(8) NOT NULL,    -- Identificador de la categoría
	  NOMBRE_CATEGORIA  VARCHAR2(20) NOT NULL,    -- Nombre de la categoria
	  DESCRIPCION_CATEGORIA  VARCHAR2(50) NULL    -- Descripcion de cada categoria
)
;

CREATE TABLE    Ciudad 
(
	  ID_CIUDAD  NUMBER(8) NOT NULL,    -- Identificador de la ciudad
	  NOMBRE  VARCHAR2(20) NOT NULL,    -- Nombre de la ciudad
	  ID_TIENDA  NUMBER(8) NULL    -- Identificador de la tienda de la ciudad
)
;

CREATE TABLE    Detalle_Pedido 
(
	  ID_PEDIDO  NUMBER(12) NOT NULL,    -- Id del pedido al que se ponen los productos, es una llave compuesta con producto
	  ID_PRODUCTO  NUMBER(30) NOT NULL,    -- Id de los productos es una llave compuesta con pedido
	  CANTIDAD  NUMBER(2) NOT NULL    -- Cantidad numerica de el producto relacionado
)
;

CREATE TABLE    Direccion 
(
	  ID_DIRECCION  NUMBER(20) NOT NULL,    -- Identificador de la dirección
	  DIRECCION_COMPLETA  VARCHAR2(50) NOT NULL,    -- Direccion completa
	  EXTRAS  VARCHAR2(200) NULL,    -- Detalles extra que el cliente provee para ubicar su direccion
	  TIPO_DIRECCION  VARCHAR2(1) NOT NULL,    -- Diferencia si la direccion es de residencia (R), de envío (E) o que no esta en uso (N)
	  ID_CIUDAD  NUMBER(8) NOT NULL,    -- Identificador de la ciudad donde esta la direccion
	  ID_CEDULA  NUMBER(20) NOT NULL,    -- Cedula de la persona a la que le pertenece la direccion
	  TIPO_ID  VARCHAR2(2) NOT NULL    -- Tipo de identificacion de la persona a la que le pertenece la direccion
)
;

CREATE TABLE    Envio 
(
	  ID_ENVIO  NUMBER(8) NOT NULL,    -- Código del envío
	  ESTADO  VARCHAR2(1) NOT NULL,    -- Estado actual del envío (entregado (E) o pendiente (P))
	  FECHA_ENTREGA_ESTIM  DATE NOT NULL,    -- Fecha en que se asume llegará el envío
	  FECHA_ENTREGA_REAL  DATE NULL,    -- Fecha en la que llegó el envío
	  TELEFONO_DESTINO  VARCHAR2(15) NOT NULL,    -- Numero de teléfono de quien resive
	  NOMBRE_DESTINO  VARCHAR2(20) NOT NULL,    -- Mombre de la persona que recibe
	  DIRECCION_ENVIO  VARCHAR2(50) NOT NULL,    -- Direccion donde se va a llevar el envío
	  EXTRAS  VARCHAR2(50) NULL,    -- Especificaciones de la direccion en caso de un conjunto
	  METODO_PAGO  VARCHAR2(1) NOT NULL,    -- Metodo como se pago
	  FECHA_PAGO  DATE NOT NULL,    -- Fecha cuando se pago
	  ID_PEDIDO  NUMBER(12) NULL    -- Pedido al que se relaciona el envio
)
;

CREATE TABLE    Inventario 
(
	  ID_PRODUCTO  NUMBER(30) NOT NULL,    -- Codigo del producto almacenado, llave compuesta con sucursal
	  ID_PROVEEDOR  NUMBER(38) NOT NULL,    -- Identificador de el proveedor de los productos
	  ID_CIUDAD  NUMBER(8) NOT NULL,    -- Identificador de la ciudad del inventario
	  EXISTENCIAS  NUMBER(5) NOT NULL,    -- Existencias actuales del producto en la tienda
	  PRECIO_BASE  NUMBER(10,2) NOT NULL    -- Precio base del producto
)
;

CREATE TABLE    Pedido 
(
	  ID_PEDIDO  NUMBER(12) NOT NULL,    -- Código del pedido
	  ESTADO_PEDIDO  VARCHAR2(2) NOT NULL,    -- Fase actual del pedido 'CA' - carrito, 'PP' -pendiente pago, 'PA' - pagado, 'RE' - rechazado
	  FECHA_PEDIDO  DATE NOT NULL,    -- Fecha de creacion/modificaciom del pedido
	  TOTAL_PEDIDO  NUMBER(12,2) NOT NULL,    -- Suma de los costos de todos los productos en el pedido
	  ID_CIUDAD  NUMBER(8) NOT NULL,    -- Código de la ciudad donde se va a enviar el pedido
	  ID_CEDULA  NUMBER(20) NOT NULL,    -- Cedula de la persona a la que le pertenece el pedido
	  TIPO_ID  VARCHAR2(2) NOT NULL    -- Tipo de identificacion de la persona a la que le pertenece el pedido
)
;

CREATE TABLE    Producto 
(
	  ID_PRODUCTO  NUMBER(30) NOT NULL,    -- Identificador del producto
	  NOMBRE_PRODUCTO  VARCHAR2(200) NOT NULL,    -- Nombre del producto
	  MARCA_PRODUCTO  VARCHAR2(50) NOT NULL,    -- Marca, editorial o productor del producto
	  REFERENCIA_PRODUCTO  VARCHAR2(50) NOT NULL,    -- Referencia del producto
	  CARACTERISTICAS_PRODUCTO  VARCHAR2(200) NULL,    -- Caracteristicas del producto
	  FOTO  VARCHAR2(50) NOT NULL,    -- Foto del producto en formato .jpg
	  ID_SUBCATEGORIA  NUMBER(8) NOT NULL,    -- Subcategoría a la que pertenece el producto
	  UNIDAD_MEDIDA  VARCHAR2(15) NOT NULL,    -- Para productos de mercado se manejan lb, kg, g, litros. Para el resto se maneja por Unidad 
	  IVA  NUMBER(4,3) NOT NULL    -- Iva del producto
)
;

CREATE TABLE    Proveedor 
(
	  ID_PROVEEDOR  NUMBER(38) NOT NULL,    -- Nit del proveedor
	  NOMBRE_PROVEEDOR  VARCHAR2(50) NOT NULL,    -- Nombre o Marca del proveedor
	  DIRECCION_PROVEEDOR  VARCHAR2(50) NOT NULL    -- Direccion donde se ubica el proveedor
)
;

CREATE TABLE    Subcategoria 
(
	  ID_SUBCATEGORIA  NUMBER(8) NOT NULL,    -- Identificador de la subcategoria
	  NOMBRE_SUBCATEGORIA  VARCHAR2(40) NOT NULL,    -- Nombre de la subcategoria
	  ID_CATEGORIA  NUMBER(8) NOT NULL    -- Identificador de la categoria a la que pertenece
)
;

CREATE TABLE    TarjetaCredito 
(
	  ID_TARJETA  NUMBER(38) NOT NULL,    -- Identificador unico dentro de la BD
	  NOMBRETITULAR  VARCHAR2(50) NOT NULL,    -- Nombre que aparece en la tarjeta de credito
	  NUMERO_TARJETA  NUMBER(30) NOT NULL,    -- Número de la tarjeta de credito, esta impresa en la tarjeta
	  FECH_EXP  VARCHAR2(5) NOT NULL,    -- Fecha de expiracion impreso en la tarjeta
	  TIPO_ID  VARCHAR2(2) NOT NULL,    -- Tipo de identificación de la persona a la que le pertenece la tarjeta de credito
	  ID_CEDULA  NUMBER(20) NOT NULL,    -- Cedula de la persona a la que le pertenece la tarjeta de credito
	  TARJETA_EN_USO  VARCHAR2(1) NOT NULL    -- Tarjeta en uso (S) o no en uso (N)
)
;

CREATE TABLE    Telefono 
(
	  ID_TELEFONO  NUMBER(10) NOT NULL,    -- Identificador dentro de la base de datos
	  NUMERO_TELEFONO  NUMBER(15) NOT NULL,    -- Número telefonico del cliente
	  TELEFONO_EN_USO  VARCHAR2(1) NOT NULL,    -- Dice si el telefono es usado por el usuario o no (S) si esta en uso o (N) no esta en uso
	  ID_CEDULA  NUMBER(20) NOT NULL,    -- Cedula del propetario del telefono
	  TIPO_ID  VARCHAR2(2) NOT NULL    -- Tipo de identificacion de la persona a la que le pertenece la tarjeta de credito
)
;

CREATE TABLE    Tienda 
(
	  ID_TIENDA  NUMBER(8) NOT NULL,    -- Identificador de la tienda
	  COSTO_ENV_LOC  NUMBER(8,2) NOT NULL,    -- Costo de envio para un pedido en la misma ciudad
	  COSTO_ENV_NAC  NUMBER(8,2) NOT NULL,    -- Costo de envio fuera de la ciudad origen
	  TIEMPO_VIDA_CARRITO  NUMBER(2) NOT NULL,    -- Tiempo (dias) de vida del carrito 
	  MIN_CANTIDAD_PRODUCTOS  NUMBER(2) NOT NULL,    -- Existencias minias admitidas en stock para poder pedir un producto.
	  ID_ADMINISTRADOR  NUMBER(38) NOT NULL    -- Identificador del administrador que maneja la tienda
)
;

CREATE TABLE    Usuario 
(
	  ID_CEDULA  NUMBER(20) NOT NULL,    -- Cedula del usuario
	  TIPO_ID  VARCHAR2(2) NOT NULL,    -- Tipo de identificación del cliente
	  PRIMER_NOMB  VARCHAR2(20) NOT NULL,    -- Primer nombre del usuario
	  SEGUNDO_NOMB  VARCHAR2(40) NULL,    -- Segundo nombre del usuario
	  PRIMER_APELL  VARCHAR2(20) NOT NULL,    -- Primer apellido del usuario
	  SEGUNDO_APELL  VARCHAR2(20) NULL,    -- Segundo apellido del usuario
	  PASSWORD  VARCHAR2(50) NOT NULL,    -- contraseña del usuario
	  FECH_NAC  DATE NOT NULL,    -- Fecha de nacimiento del cliente  The Oracle standard date format for input and output is DD-MON-YY e.g., 01-JAN-17
	  GENERO  VARCHAR2(1) NOT NULL,    -- Genero del cliente
	  EMAIL  VARCHAR2(50) NOT NULL,    -- e-mail con el que se registra el cliente
	  NICKNAME  VARCHAR2(20) NOT NULL    -- Nombre de usuario seleccionado por el cliente
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE    Administrador  IS 'Persona responsable de RAFASE'
;

COMMENT ON COLUMN    Administrador .  ID_ADMINISTRADOR  IS 'N. de identificacion del administrador'
;

COMMENT ON COLUMN    Administrador .  NOMBRE_ADMINISTRADOR  IS 'Nombre del administrador'
;

COMMENT ON COLUMN    Administrador .  EMAIL  IS 'Correo electrónico del administrador'
;

COMMENT ON COLUMN    Administrador .  CONTRASENA  IS 'Contraseña del administrador'
;

COMMENT ON TABLE    Categoria  IS 'Categoria general de productos (ENTRETENIMIENTO, HOGAR, MERCADO)'
;

COMMENT ON COLUMN    Categoria .  ID_CATEGORIA  IS 'Identificador de la categoría'
;

COMMENT ON COLUMN    Categoria .  NOMBRE_CATEGORIA  IS 'Nombre de la categoria'
;

COMMENT ON COLUMN    Categoria .  DESCRIPCION_CATEGORIA  IS 'Descripcion de cada categoria'
;

COMMENT ON TABLE    Ciudad  IS 'Almacena nombres de ciudades'
;

COMMENT ON COLUMN    Ciudad .  ID_CIUDAD  IS 'Identificador de la ciudad'
;

COMMENT ON COLUMN    Ciudad .  NOMBRE  IS 'Nombre de la ciudad'
;

COMMENT ON COLUMN    Ciudad .  ID_TIENDA  IS 'Identificador de la tienda de la ciudad'
;

COMMENT ON TABLE    Detalle_Pedido  IS 'Tabla de rompimiento entre muchos pedidos a muchos productos, guarda la cantidad de un producto en un pedido'
;

COMMENT ON COLUMN    Detalle_Pedido .  ID_PEDIDO  IS 'Id del pedido al que se ponen los productos, es una llave compuesta con producto'
;

COMMENT ON COLUMN    Detalle_Pedido .  ID_PRODUCTO  IS 'Id de los productos es una llave compuesta con pedido'
;

COMMENT ON COLUMN    Detalle_Pedido .  CANTIDAD  IS 'Cantidad numerica de el producto relacionado'
;

COMMENT ON TABLE    Direccion  IS 'Almacena direcciones residenciales y de entrega'
;

COMMENT ON COLUMN    Direccion .  ID_DIRECCION  IS 'Identificador de la dirección'
;

COMMENT ON COLUMN    Direccion .  DIRECCION_COMPLETA  IS 'Direccion completa'
;

COMMENT ON COLUMN    Direccion .  EXTRAS  IS 'Detalles extra que el cliente provee para ubicar su direccion'
;

COMMENT ON COLUMN    Direccion .  TIPO_DIRECCION  IS 'Diferencia si la direccion es de residencia (R), de envío (E) o que no esta en uso (N)'
;

COMMENT ON COLUMN    Direccion .  ID_CIUDAD  IS 'Identificador de la ciudad donde esta la direccion'
;

COMMENT ON COLUMN    Direccion .  ID_CEDULA  IS 'Cedula de la persona a la que le pertenece la direccion'
;

COMMENT ON COLUMN    Direccion .  TIPO_ID  IS 'Tipo de identificacion de la persona a la que le pertenece la direccion'
;

COMMENT ON TABLE    Envio  IS 'Control de envios'
;

COMMENT ON COLUMN    Envio .  ID_ENVIO  IS 'Código del envío'
;

COMMENT ON COLUMN    Envio .  ESTADO  IS 'Estado actual del envío (entregado (E) o pendiente (P))'
;

COMMENT ON COLUMN    Envio .  FECHA_ENTREGA_ESTIM  IS 'Fecha en que se asume llegará el envío'
;

COMMENT ON COLUMN    Envio .  FECHA_ENTREGA_REAL  IS 'Fecha en la que llegó el envío'
;

COMMENT ON COLUMN    Envio .  TELEFONO_DESTINO  IS 'Numero de teléfono de quien resive'
;

COMMENT ON COLUMN    Envio .  NOMBRE_DESTINO  IS 'Mombre de la persona que recibe'
;

COMMENT ON COLUMN    Envio .  DIRECCION_ENVIO  IS 'Direccion donde se va a llevar el envío'
;

COMMENT ON COLUMN    Envio .  EXTRAS  IS 'Especificaciones de la direccion en caso de un conjunto'
;

COMMENT ON COLUMN    Envio .  METODO_PAGO  IS 'Metodo como se pago'
;

COMMENT ON COLUMN    Envio .  FECHA_PAGO  IS 'Fecha cuando se pago'
;

COMMENT ON COLUMN    Envio .  ID_PEDIDO  IS 'Pedido al que se relaciona el envio'
;

COMMENT ON TABLE    Inventario  IS 'Relacion que representa Inventario de productos actual en bodega de cada sucursal - tabla de rompimiento de muchos productos en muchas sucursales'
;

COMMENT ON COLUMN    Inventario .  ID_PRODUCTO  IS 'Codigo del producto almacenado, llave compuesta con sucursal'
;

COMMENT ON COLUMN    Inventario .  ID_PROVEEDOR  IS 'Identificador de el proveedor de los productos'
;

COMMENT ON COLUMN    Inventario .  ID_CIUDAD  IS 'Identificador de la ciudad del inventario'
;

COMMENT ON COLUMN    Inventario .  EXISTENCIAS  IS 'Existencias actuales del producto en la tienda'
;

COMMENT ON COLUMN    Inventario .  PRECIO_BASE  IS 'Precio base del producto'
;

COMMENT ON TABLE    Pedido  IS 'Ordenes de compra de los clientes, pedidos que un usuario registrado '
;

COMMENT ON COLUMN    Pedido .  ID_PEDIDO  IS 'Código del pedido'
;

COMMENT ON COLUMN    Pedido .  ESTADO_PEDIDO  IS 'Fase actual del pedido ''CA'' - carrito, ''PP'' -pendiente pago, ''PA'' - pagado, ''RE'' - rechazado'
;

COMMENT ON COLUMN    Pedido .  FECHA_PEDIDO  IS 'Fecha de creacion/modificaciom del pedido'
;

COMMENT ON COLUMN    Pedido .  TOTAL_PEDIDO  IS 'Suma de los costos de todos los productos en el pedido'
;

COMMENT ON COLUMN    Pedido .  ID_CIUDAD  IS 'Código de la ciudad donde se va a enviar el pedido'
;

COMMENT ON COLUMN    Pedido .  ID_CEDULA  IS 'Cedula de la persona a la que le pertenece el pedido'
;

COMMENT ON COLUMN    Pedido .  TIPO_ID  IS 'Tipo de identificacion de la persona a la que le pertenece el pedido'
;

COMMENT ON TABLE    Producto  IS 'Lista de productos ofrecidos por RAFASE'
;

COMMENT ON COLUMN    Producto .  ID_PRODUCTO  IS 'Identificador del producto'
;

COMMENT ON COLUMN    Producto .  NOMBRE_PRODUCTO  IS 'Nombre del producto'
;

COMMENT ON COLUMN    Producto .  MARCA_PRODUCTO  IS 'Marca, editorial o productor del producto'
;

COMMENT ON COLUMN    Producto .  REFERENCIA_PRODUCTO  IS 'Referencia del producto'
;

COMMENT ON COLUMN    Producto .  CARACTERISTICAS_PRODUCTO  IS 'Caracteristicas del producto'
;

COMMENT ON COLUMN    Producto .  FOTO  IS 'Foto del producto en formato .jpg'
;

COMMENT ON COLUMN    Producto .  ID_SUBCATEGORIA  IS 'Subcategoría a la que pertenece el producto'
;

COMMENT ON COLUMN    Producto .  UNIDAD_MEDIDA  IS 'Para productos de mercado se manejan lb, kg, g, litros. Para el resto se maneja por Unidad '
;

COMMENT ON COLUMN    Producto .  IVA  IS 'Iva del producto'
;

COMMENT ON TABLE    Proveedor  IS 'Marca o empresa que provee productos a RAFASE'
;

COMMENT ON COLUMN    Proveedor .  ID_PROVEEDOR  IS 'Nit del proveedor'
;

COMMENT ON COLUMN    Proveedor .  NOMBRE_PROVEEDOR  IS 'Nombre o Marca del proveedor'
;

COMMENT ON COLUMN    Proveedor .  DIRECCION_PROVEEDOR  IS 'Direccion donde se ubica el proveedor'
;

COMMENT ON TABLE    Subcategoria  IS 'Grupo especifico al que pertenece el producto'
;

COMMENT ON COLUMN    Subcategoria .  ID_SUBCATEGORIA  IS 'Identificador de la subcategoria'
;

COMMENT ON COLUMN    Subcategoria .  NOMBRE_SUBCATEGORIA  IS 'Nombre de la subcategoria'
;

COMMENT ON COLUMN    Subcategoria .  ID_CATEGORIA  IS 'Identificador de la categoria a la que pertenece'
;

COMMENT ON TABLE    TarjetaCredito  IS 'Tarjetas de credito de usuarios guardadas en el sistema'
;

COMMENT ON COLUMN    TarjetaCredito .  ID_TARJETA  IS 'Identificador unico dentro de la BD'
;

COMMENT ON COLUMN    TarjetaCredito .  NOMBRETITULAR  IS 'Nombre que aparece en la tarjeta de credito'
;

COMMENT ON COLUMN    TarjetaCredito .  NUMERO_TARJETA  IS 'Número de la tarjeta de credito, esta impresa en la tarjeta'
;

COMMENT ON COLUMN    TarjetaCredito .  FECH_EXP  IS 'Fecha de expiracion impreso en la tarjeta'
;

COMMENT ON COLUMN    TarjetaCredito .  TIPO_ID  IS 'Tipo de identificación de la persona a la que le pertenece la tarjeta de credito'
;

COMMENT ON COLUMN    TarjetaCredito .  ID_CEDULA  IS 'Cedula de la persona a la que le pertenece la tarjeta de credito'
;

COMMENT ON COLUMN    TarjetaCredito .  TARJETA_EN_USO  IS 'Tarjeta en uso (S) o no en uso (N)'
;

COMMENT ON TABLE    Telefono  IS 'Almacena los números telefónicos de los usuarios'
;

COMMENT ON COLUMN    Telefono .  ID_TELEFONO  IS 'Identificador dentro de la base de datos'
;

COMMENT ON COLUMN    Telefono .  NUMERO_TELEFONO  IS 'Número telefonico del cliente'
;

COMMENT ON COLUMN    Telefono .  TELEFONO_EN_USO  IS 'Dice si el telefono es usado por el usuario o no (S) si esta en uso o (N) no esta en uso'
;

COMMENT ON COLUMN    Telefono .  ID_CEDULA  IS 'Cedula del propetario del telefono'
;

COMMENT ON COLUMN    Telefono .  TIPO_ID  IS 'Tipo de identificacion de la persona a la que le pertenece la tarjeta de credito'
;

COMMENT ON TABLE    Tienda  IS 'Tabla con los detalles generales de la tienda'
;

COMMENT ON COLUMN    Tienda .  ID_TIENDA  IS 'Identificador de la tienda'
;

COMMENT ON COLUMN    Tienda .  COSTO_ENV_LOC  IS 'Costo de envio para un pedido en la misma ciudad'
;

COMMENT ON COLUMN    Tienda .  COSTO_ENV_NAC  IS 'Costo de envio fuera de la ciudad origen'
;

COMMENT ON COLUMN    Tienda .  TIEMPO_VIDA_CARRITO  IS 'Tiempo (dias) de vida del carrito '
;

COMMENT ON COLUMN    Tienda .  MIN_CANTIDAD_PRODUCTOS  IS 'Existencias minias admitidas en stock para poder pedir un producto.'
;

COMMENT ON COLUMN    Tienda .  ID_ADMINISTRADOR  IS 'Identificador del administrador que maneja la tienda'
;

COMMENT ON TABLE    Usuario  IS 'Un usuario registrado que puede realizar compras dentro del sistema, almacenar tarjetas de credito y guardar un carrito.'
;

COMMENT ON COLUMN    Usuario .  ID_CEDULA  IS 'Cedula del usuario'
;

COMMENT ON COLUMN    Usuario .  TIPO_ID  IS 'Tipo de identificación del cliente'
;

COMMENT ON COLUMN    Usuario .  PRIMER_NOMB  IS 'Primer nombre del usuario'
;

COMMENT ON COLUMN    Usuario .  SEGUNDO_NOMB  IS 'Segundo nombre del usuario'
;

COMMENT ON COLUMN    Usuario .  PRIMER_APELL  IS 'Primer apellido del usuario'
;

COMMENT ON COLUMN    Usuario .  SEGUNDO_APELL  IS 'Segundo apellido del usuario'
;

COMMENT ON COLUMN    Usuario .  PASSWORD  IS 'contraseña del usuario'
;

COMMENT ON COLUMN    Usuario .  FECH_NAC  IS 'Fecha de nacimiento del cliente  The Oracle standard date format for input and output is DD-MON-YY e.g., 01-JAN-17'
;

COMMENT ON COLUMN    Usuario .  GENERO  IS 'Genero del cliente'
;

COMMENT ON COLUMN    Usuario .  EMAIL  IS 'e-mail con el que se registra el cliente'
;

COMMENT ON COLUMN    Usuario .  NICKNAME  IS 'Nombre de usuario seleccionado por el cliente'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE    Administrador  
 ADD CONSTRAINT   PK_ADMINISTRADOR 
	PRIMARY KEY (  ID_ADMINISTRADOR ) 
 USING INDEX
;

ALTER TABLE    Administrador  
 ADD CONSTRAINT   CK_ADMINISTRADOR  CHECK (ID_ADMINISTRADOR > 0)
;

ALTER TABLE    Categoria  
 ADD CONSTRAINT   PK_CATEGORIA 
	PRIMARY KEY (  ID_CATEGORIA ) 
 USING INDEX
;

ALTER TABLE    Categoria  
 ADD CONSTRAINT   CK_CATEGORIA_T_CATEGORIA  CHECK (ID_CATEGORIA > 0)
;

ALTER TABLE    Ciudad  
 ADD CONSTRAINT   PK_CIUDAD 
	PRIMARY KEY (  ID_CIUDAD ) 
 USING INDEX
;

ALTER TABLE    Ciudad  
 ADD CONSTRAINT   CK_CIUDAD_T_CIUDAD  CHECK (ID_CIUDAD > 0)
;

ALTER TABLE    Ciudad  
 ADD CONSTRAINT   CK_TIENDA_T_CIUDAD  CHECK (ID_TIENDA > 0)
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   PK_PEDIDO_PRODUCTO 
	PRIMARY KEY (  ID_PEDIDO ,  ID_PRODUCTO ) 
 USING INDEX
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   CK_CANTIDAD  CHECK (CANTIDAD > 0)
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   CK_PEDIDO_T_DETALLEPEDIDO  CHECK (ID_PEDIDO > 0)
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   CK_PRODUCTO_T_DETALLEPEDIDO  CHECK (ID_PRODUCTO > 0)
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   PK_DIRECCION 
	PRIMARY KEY (  ID_DIRECCION ) 
 USING INDEX
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   CK_TIPO_DIRECCION  CHECK (TIPO_DIRECCION IN ('R','E','N'))
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   CK_DIRECCION_T_DIRECCION  CHECK (ID_DIRECCION > 0)
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   CK_CIUDAD_T_DIRECCION  CHECK (ID_CIUDAD > 0)
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   CK_TIPO_ID_T_DIRECCION  CHECK (TIPO_ID IN ('CC','CE'))
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   CK_CEDULA_T_DIRECCION  CHECK (ID_CEDULA > 0)
;

ALTER TABLE    Envio  
 ADD CONSTRAINT   PK_ENVIO 
	PRIMARY KEY (  ID_ENVIO ) 
 USING INDEX
;

ALTER TABLE    Envio  
 ADD CONSTRAINT   ESTADO  CHECK (ESTADO IN ('E', 'P'))
;

ALTER TABLE    Envio  
 ADD CONSTRAINT   CK_ENVIO_T_ENVIO  CHECK (ID_ENVIO > 0)
;

ALTER TABLE    Envio  
 ADD CONSTRAINT   CK_PEDIDO_T_ENVIO  CHECK (ID_PEDIDO > 0)
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   PK_INVENTARIO 
	PRIMARY KEY (  ID_PRODUCTO ,  ID_PROVEEDOR ,  ID_CIUDAD ) 
 USING INDEX
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   CK_EXISTENCIAS  CHECK (EXISTENCIAS > 0)
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   CK_PRODUCTO_T_INVENTARIO  CHECK (ID_PRODUCTO > 0)
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   CK_CIUDAD_T_INVENTARIO  CHECK (ID_CIUDAD > 0)
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   CK_PROVEEDOR_T_INVENTARIO  CHECK (ID_PROVEEDOR > 0)
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   CK_PRECIO_BASE  CHECK (PRECIO_BASE >= 0)
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   PK_PEDIDO 
	PRIMARY KEY (  ID_PEDIDO ) 
 USING INDEX
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_TOTAL_PEDIDO  CHECK (TOTAL_PEDIDO > 0)
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_PEDIDO_T_PEDIDO  CHECK (ID_PEDIDO > 0)
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_CIUDAD_T_PEDIDO  CHECK (ID_CIUDAD > 0)
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_CEDULA_T_PEDIDO  CHECK (ID_CEDULA > 0)
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_TIPO_ID_T_PEDIDO  CHECK (TIPO_ID IN ('CC','CE'))
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   CK_ESTADO_PEDIDO  CHECK (ESTADO_PEDIDO IN ('CA','PP','PA','RE'))
;

ALTER TABLE    Producto  
 ADD CONSTRAINT   PK_PRODUCTO 
	PRIMARY KEY (  ID_PRODUCTO ) 
 USING INDEX
;

ALTER TABLE    Producto  
 ADD CONSTRAINT   CK_PRODUCTO_T_PRODUCTO  CHECK (ID_PRODUCTO > 0)
;

ALTER TABLE    Producto  
 ADD CONSTRAINT   CK_SUBCATEGORIA_T_PRODUCTO  CHECK (ID_SUBCATEGORIA > 0)
;

ALTER TABLE    Producto  
 ADD CONSTRAINT   CK_IVA  CHECK (IVA >= 0)
;

ALTER TABLE    Proveedor  
 ADD CONSTRAINT   PK_PROVEEDOR 
	PRIMARY KEY (  ID_PROVEEDOR ) 
 USING INDEX
;

ALTER TABLE    Proveedor  
 ADD CONSTRAINT   CK_PROVEEDOR_T_PROVEEDOR  CHECK (ID_PROVEEDOR > 0)
;

ALTER TABLE    Subcategoria  
 ADD CONSTRAINT   PK_SUBCATEGORIA 
	PRIMARY KEY (  ID_SUBCATEGORIA ) 
 USING INDEX
;

ALTER TABLE    Subcategoria  
 ADD CONSTRAINT   CK_CATEGORIA_T_SUBCATEGORIA  CHECK (ID_CATEGORIA > 0)
;

ALTER TABLE    Subcategoria  
 ADD CONSTRAINT   CK_SUBCATEGORIA_T_SUBCATEGORIA  CHECK (ID_SUBCATEGORIA > 0)
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   PK_METODO_PAGO 
	PRIMARY KEY (  ID_TARJETA ) 
 USING INDEX
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   CK_NUMERO_TARJETA  CHECK (NUMERO_TARJETA > 0)
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   CK_TARJETA_T_TARJETACREDITO  CHECK (ID_TARJETA > 0)
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   CK_CEDULA_T_TARJETACREDITO  CHECK (ID_CEDULA > 0)
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   CK_TIPO_ID_T_TARJETACREDITO  CHECK (TIPO_ID IN ('CC','CE'))
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   CK_TARJETA_EN_USO  CHECK (TARJETA_EN_USO IN ('S','N'))
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   PK_TELEFONO 
	PRIMARY KEY (  ID_TELEFONO ) 
 USING INDEX
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   CK_NUMERO_TELEFONO  CHECK (NUMERO_TELEFONO > 0)
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   CK_TELEFONO_EN_USO  CHECK (TELEFONO_EN_USO IN ('S','N'))
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   CK_TELEFONO_T_TELEFONO  CHECK (ID_TELEFONO > 0)
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   CK_TIPO_ID_T_TELEFONO  CHECK (TIPO_ID IN ('CC','CE'))
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   CK_CEDULA_T_TELEFONO  CHECK (ID_CEDULA > 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   PK_TIENDA 
	PRIMARY KEY (  ID_TIENDA ) 
 USING INDEX
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_TIEMPO_VIDA_CARRITO  CHECK (TIEMPO_VIDA_CARRITO > 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_MIN_CANTIDAD_PRODUCTOS  CHECK (MIN_CANTIDAD_PRODUCTOS > 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_COSTO_ENV_LOC  CHECK (COSTO_ENV_LOC >= 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_COSTO_ENV_NAC  CHECK (COSTO_ENV_NAC >= 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_TIENDA_T_TIENDA  CHECK (ID_TIENDA > 0)
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   CK_ADMINISTRADOR_T_TIENDA  CHECK (ID_ADMINISTRADOR > 0)
;

ALTER TABLE    Usuario  
 ADD CONSTRAINT   PK_USUARIO 
	PRIMARY KEY (  ID_CEDULA ,  TIPO_ID ) 
 USING INDEX
;

ALTER TABLE    Usuario  
 ADD CONSTRAINT   CK_CEDULA_T_CEDULA  CHECK (ID_CEDULA > 0)
;

ALTER TABLE    Usuario  
 ADD CONSTRAINT   CK_GENERO  CHECK (GENERO IN ('F','M','O'))
;

ALTER TABLE    Usuario  
 ADD CONSTRAINT   CK_TIPO_ID_T_CEDULA  CHECK (TIPO_ID IN ('CC','CE'))
;

/* Create Foreign Key Constraints */

ALTER TABLE    Ciudad  
 ADD CONSTRAINT   FK_CIUDAD_TIENDA 
	FOREIGN KEY (  ID_TIENDA ) REFERENCES    Tienda  (  ID_TIENDA )
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   FK_PEDIDO_PRODUCTO_PEDIDO 
	FOREIGN KEY (  ID_PEDIDO ) REFERENCES    Pedido  (  ID_PEDIDO )
;

ALTER TABLE    Detalle_Pedido  
 ADD CONSTRAINT   FK_PEDIDO_PRODUCTO_PRODUCTO 
	FOREIGN KEY (  ID_PRODUCTO ) REFERENCES    Producto  (  ID_PRODUCTO )
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   FK_DIRECCION_CIUDAD 
	FOREIGN KEY (  ID_CIUDAD ) REFERENCES    Ciudad  (  ID_CIUDAD )
;

ALTER TABLE    Direccion  
 ADD CONSTRAINT   FK_DIRECCION_USUARIO 
	FOREIGN KEY (  ID_CEDULA ,  TIPO_ID ) REFERENCES    Usuario  (  ID_CEDULA ,  TIPO_ID )
;

ALTER TABLE    Envio  
 ADD CONSTRAINT   FK_ENVIO_PEDIDO 
	FOREIGN KEY (  ID_PEDIDO ) REFERENCES    Pedido  (  ID_PEDIDO )
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   FK_INVENTARIO_CIUDAD 
	FOREIGN KEY (  ID_CIUDAD ) REFERENCES    Ciudad  (  ID_CIUDAD )
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   FK_INVENTARIO_PRODUCTO 
	FOREIGN KEY (  ID_PRODUCTO ) REFERENCES    Producto  (  ID_PRODUCTO )
;

ALTER TABLE    Inventario  
 ADD CONSTRAINT   FK_INVENTARIO_PROVEEDOR 
	FOREIGN KEY (  ID_PROVEEDOR ) REFERENCES    Proveedor  (  ID_PROVEEDOR )
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   FK_PEDIDO_CIUDAD 
	FOREIGN KEY (  ID_CIUDAD ) REFERENCES    Ciudad  (  ID_CIUDAD )
;

ALTER TABLE    Pedido  
 ADD CONSTRAINT   FK_PEDIDO_USUARIO 
	FOREIGN KEY (  ID_CEDULA ,  TIPO_ID ) REFERENCES    Usuario  (  ID_CEDULA ,  TIPO_ID )
;

ALTER TABLE    Producto  
 ADD CONSTRAINT   FK_PRODUCTO_SUBCATEGORIA 
	FOREIGN KEY (  ID_SUBCATEGORIA ) REFERENCES    Subcategoria  (  ID_SUBCATEGORIA )
;

ALTER TABLE    Subcategoria  
 ADD CONSTRAINT   FK_SUBCATEGORIA_CATEGORIA 
	FOREIGN KEY (  ID_CATEGORIA ) REFERENCES    Categoria  (  ID_CATEGORIA )
;

ALTER TABLE    TarjetaCredito  
 ADD CONSTRAINT   FK_TARJETACREDITO_USUARIO 
	FOREIGN KEY (  ID_CEDULA ,  TIPO_ID ) REFERENCES    Usuario  (  ID_CEDULA ,  TIPO_ID )
;

ALTER TABLE    Telefono  
 ADD CONSTRAINT   FK_TELEFONO_USUARIO 
	FOREIGN KEY (  ID_CEDULA ,  TIPO_ID ) REFERENCES    Usuario  (  ID_CEDULA ,  TIPO_ID )
;

ALTER TABLE    Tienda  
 ADD CONSTRAINT   FK_TIENDA_ADMINISTRADOR 
	FOREIGN KEY (  ID_ADMINISTRADOR ) REFERENCES    Administrador  (  ID_ADMINISTRADOR )
;
